# Generated by Django 4.2.7 on 2023-12-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezume_app', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezume_app.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezume_app.blog')),
            ],
        ),
    ]
